### ISSUE TITLE
Idea: Use annotations(e.g. maxLength) to improve fast-check performance

### ISSUE THREAD

**Issue by jessekelly881** [fp-ts/schema#33]
Just an idea, but do you think it would be possible/a good idea to be able to use annotations to improve the performance of fast-check? Given the way that Arbitrary is implemented for example this doesn't see too difficult to do for basic filters and it would likely greatly improve the speed of fast check generated values. 

For example, it would make sense for the nonEmpty, and maxLength in this code

```js
const Password = pipe(
  S.string,
  S.nonEmpty, // adds annotation: {nonEmpty: true}
  S.maxLength(10) // adds annotation {maxLength: 10}
);
```

to also be picked up by fast check and create an arbitrary like:

```js
fc.string({ maxLength: 10, minLength: 1})
```

I see that you have already implemented something similar for json schema. But the json schema annotations seem too specific. For example, in the minLength function in data/filter you set ` jsonSchema: { exclusiveMinimum: min }`. Maybe this could be replaced with `minLength: min` and interpreted properly in the json schema module? This actually seems like a better solution sense, for example, endsWith and includes both set the jsonSchema.pattern prop which means they can't be used together. If "includes" and "endsWith" annotations were set by their respective functions the two values could be later combined into the correct json schema value. 

Maybe this is something you are already working on. And if so sorry for creating an issue.

**Comment by gcanti** [comment]
Thank you for the suggestions and you're right, the management of annotations is too simplistic at the moment and needs to be heavily improved.

For example, annotations related to jsonSchema could be accumulated and then left to the interpreter to decide what to do.

>  Maybe this could be replaced with minLength: min

If I'm not mistaken it's already like that https://github.com/fp-ts/schema/blob/924e4302c4a7877bc20e7cb8167862bbac64f9b8/src/data/filter.ts#L156

**Comment by gcanti** [comment]
> for example, endsWith and includes both set the jsonSchema.pattern prop which means they can't be used together.

Let's see a concrete example:

```ts
const schema = pipe(S.string, S.endsWith("end"), S.includes("search"))
console.log("%o", schema.ast)
```

```ts
{
  _tag: 'Refinement',
  from: {
    _tag: 'Refinement',
    from: {
      _tag: 'StringKeyword',
      annotations: { '@fp-ts/schema/annotation/TitleId': 'string' }
    },
    refinement: [Function (anonymous)] { [length]: 1, [name]: '' },
    annotations: {
      '@fp-ts/schema/annotation/DescriptionId': 'a string ending with "end"',
      '@fp-ts/schema/annotation/JSONSchemaId': { pattern: '^.*end$' },
      '@fp-ts/schema/annotation/CustomId': { type: 'endsWith', endsWith: 'end' }
    }
  },
  refinement: [Function (anonymous)] { [length]: 1, [name]: '' },
  annotations: {
    '@fp-ts/schema/annotation/DescriptionId': 'a string including "search"',
    '@fp-ts/schema/annotation/JSONSchemaId': { pattern: '.*search.*' },
    '@fp-ts/schema/annotation/CustomId': { type: 'includes', includes: 'search' }
  }
}
```

Perhaps the DX could be improved but it seems to me that all the meta information necessary for the JSON Schema compiler to make decisions is already there
