### ISSUE TITLE
add trim combinator

### ISSUE THREAD

**Issue by gcanti** [fp-ts/schema#35]
## 🚀 Feature request

Add `/data/parser.ts#trim` combinator
Add `/data/filter.ts#trim` combinator

### Desired Behavior

Related: [`z.string().trim(); // trim whitespace`](https://zod.dev/?id=strings)

### Suggested Solution

Use `transform` API

**Comment by FedericoBiccheddu** [comment]
The merge didn't close this issue.

I have updated the description using a different keyword, but it is not retroactive.
