### ISSUE TITLE
Add link to docs in repo "about" section

### ISSUE THREAD

**Issue by jessekelly881** [fp-ts/schema#81]
Can we add a link to the docs site in the repo description? I had to go looking for it. Assuming this is the right url https://fp-ts.github.io/schema it doesn't seem to be up to date. Same with @fp-ts/optics

<img width="323" alt="Screen Shot 2023-02-09 at 11 50 45 PM" src="https://user-images.githubusercontent.com/22938931/217956938-d1579428-5017-4fff-b165-1f770dbe4191.png">

**Comment by gcanti** [comment]
Done

**Comment by jessekelly881** [comment]
Thanks!
