### ISSUE TITLE
Arbitrary for fromValues should return ReadonlyArray not ReadonlySet. 

### ISSUE THREAD

**Issue by zestsystem** [fp-ts/schema#91]
## 🚀 Feature request
I think arbitrary for fromValues function in ReadonlySet should return a  ReadonlyArray, not a ReadonlySet. This is because fromValues function expects an array or tuple and requires that I transform the array before it goes through decode. 

Loving the dev experince of this library btw, so thank you so much!

### Current Behavior
Given the schema: 
 ```ts 
export const InviteTeamMembersInput = S.struct({
    leaderId: UUID,
    teamId: UUID,
    membersToInvite: fromValues(UUID),
})
```
and the test case: 
```ts
const inviteTeamMembersInputArb = A.arbitrary(InviteTeamMembersInput)(fc);

it('successfully invites team members', () => {
    fc.assert(
        fc.property(
                inviteTeamMembersInputArb,
                // need to transform the readonlySet to array to make this test pass since fromValues expects array or tuple
                .map(input) => {
                    return { ...input, membersToInvite: Array.from(input.membersToInvite) };
                }),
            input => {
                const result = pipe(
                   input,
                   S.decode(InviteTeamMembersInput)
                  )
                 expect(result).toBeRight();
            }
        )
    );
});


```

Not transforming the set to array gives me this error:
```bash
Received Left: {"message": "Validation failed.", "name": "ValidationFailed", "parseErrors": "1 error(s) found
└─ key \"membersToInvite\"
   └─ Expected tuple or array, actual {}", "type": "UserError"}
```

### Desired Behavior
```ts
const inviteTeamMembersInputArb = A.arbitrary(InviteTeamMembersInput)(fc);

it('successfully invites team members', () => {
    fc.assert(
        fc.property(
                inviteTeamMembersInputArb,
                // no need to transform data
            input => {
                const result = pipe(
                   input,
                   S.decode(InviteTeamMembersInput)
                  )
                 expect(result).toBeRight();
            }
        )
    );
});


```

| Software      | Version(s) |
| ------------- | ---------- |
| @fp-ts/schema |       0.1.3     |
| TypeScript    |       4.9.5     |

**Comment by gcanti** [comment]
> I think arbitrary for fromValues function in ReadonlySet should return a ReadonlyArray, not a ReadonlySet

Given an `Schema<A>`, the main use case is to build an `Arbitrary<A>`.

Suppose the schema has transformations "inside", which means that if we use the `Parser` compiler we will have a decoding from a certain type `I` to type `A`. If we produce an `Arbitrary<I>` (which is currently not technically possible because we are not tracking the `I` type but only the `A` type in `Schema`) as you suggest, what happens if instead a user wants to have an `Arbitrary<A>`?

**Comment by zestsystem** [comment]
Thanks for the prompt response. Yeah I realize it would be very annoying to test any function that occurs after the decode process(i.e. Team arbitrary starts returning array with dulicate UUIDs when you expect a set). 

I just wanted to raise attention to the fact that when testing a function that contains S.decode, one would have to convert it to array every time to make the test pass. 

Thank you. I will close this issue now. 

On an unrelated note, is there a way to pick out the schema of a member from a union schema? For example: 

```ts
const SomeUnion = S.union(S.literal('A'), S.literal('B'), S.literal('C'))

const Stuff = S.struct({
type: pipe(SomeUnion, S.pickMember('A'))
});

```

**Comment by gcanti** [comment]
To answer this question, and others in the same vein, the process to understand if it is possible is composed of two phases:
1) Is it possible to obtain the thing at the type-level, i.e., ignoring for a moment how to do it at runtime, am I able to write the signature of a function that gets me the desired result?
2) If the answer to point 1) is positive, then it is possible to try to write its implementation, relying on the fact that each `Schema` is completely introspectable through its `ast` property.

Therefore, in this specific case:
1) Given the type `type SomeUnion = "A" | "B" | "C"`, how do I obtain the type `type Result = { type: "A" }`?

**Comment by gcanti** [comment]
In other words, am I able to define a helper type `MyHelper` such that `MyHelper<SomeUnion, ...other params...> = { type: "A" }`?

If so, then I can try to define a corresponding concrete function `myHelper(schema, ...other params...)` to which I pass the `SomeUnion` schema and that is able to return an `Schema<{ type: "A" }>`

**Comment by gcanti** [comment]
Practical example:

Phase 1 (only typings)

```ts
type PickMember<Union extends string, Member extends Union> = Extract<Union, Member>
type Test = PickMember<"A" | "B" | "C", "A"> // => "A"
```

same functionality of `PickMember` but declared as a function involving `Schema`s

```ts
import * as S from "@fp-ts/schema"

declare const const pickMember: <Union extends string, Member extends Union>(
  union: S.Schema<Union>,
  member: Member
) => S.Schema<Extract<Union, Member>>
```

Phase 2 (implementation)

```ts
import * as AST from "@fp-ts/schema/AST"

const pickMember = <Union extends string, Member extends Union>(
  union: S.Schema<Union>,
  member: Member
): S.Schema<Extract<Union, Member>> => {
  if (AST.isUnion(union.ast)) {
    const types = union.ast.types
    for (const type of types) {
      if (AST.isLiteral(type) && type.literal === member) {
        return S.make(type)
      }
    }
  }
  throw new Error("cannot pickMember")
}

const SomeUnion = S.union(S.literal("A"), S.literal("B"), S.literal("C"))

const Stuff = S.struct({
  type: pickMember(SomeUnion, "A")
})

console.log(S.decodeOrThrow(Stuff)({ type: "A" }))
console.log(S.decodeOrThrow(Stuff)({ type: "foo" })) // throws
```

**Comment by zestsystem** [comment]
Wow, thank you for the thorough explanation and the practical example to top it off.
